//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Appclusive.PS.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Appclusive.PS.Client.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to &apos;{0}&apos; ....
        /// </summary>
        internal static string EnterServer_ProcessRecord__Login {
            get {
                return ResourceManager.GetString("EnterServer_ProcessRecord__Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to &apos;{0}&apos; (&apos;{1}&apos;) FAILED..
        /// </summary>
        internal static string EnterServer_ProcessRecord__LoginFailed {
            get {
                return ResourceManager.GetString("EnterServer_ProcessRecord__LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to &apos;{0}&apos; (&apos;{1}&apos;) SUCCEEDED..
        /// </summary>
        internal static string EnterServer_ProcessRecord__LoginSucceeded {
            get {
                return ResourceManager.GetString("EnterServer_ProcessRecord__LoginSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiBaseUri &apos;{0}&apos; and ParameterSetName &apos;{1}&apos;..
        /// </summary>
        internal static string EnterServer_ProcessRecord__ShouldProcess {
            get {
                return ResourceManager.GetString("EnterServer_ProcessRecord__ShouldProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving moduleContext to module variable FAILED..
        /// </summary>
        internal static string ImportConfiguration_ProcessRecord__SaveToModuleVariableFailed {
            get {
                return ResourceManager.GetString("ImportConfiguration_ProcessRecord__SaveToModuleVariableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration from &apos;{0}&apos;.
        /// </summary>
        internal static string ImportConfiguration_ProcessRecord__ShouldProcess {
            get {
                return ResourceManager.GetString("ImportConfiguration_ProcessRecord__ShouldProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Creating ConfigurationFileMap FAILED..
        /// </summary>
        internal static string ModuleConfiguration_GetModuleContextConfigurationSection__FileMapCreationFailed {
            get {
                return ResourceManager.GetString("ModuleConfiguration_GetModuleContextConfigurationSection__FileMapCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Opening Configuration FAILED due to no file..
        /// </summary>
        internal static string ModuleConfiguration_GetModuleContextConfigurationSection__NoConfigurationFile {
            get {
                return ResourceManager.GetString("ModuleConfiguration_GetModuleContextConfigurationSection__NoConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Opening Configuration FAILED..
        /// </summary>
        internal static string ModuleConfiguration_GetModuleContextConfigurationSection__OpenConfigurationFailed {
            get {
                return ResourceManager.GetString("ModuleConfiguration_GetModuleContextConfigurationSection__OpenConfigurationFailed" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Opening ConfigurationSection &apos;{1}&apos; FAILED..
        /// </summary>
        internal static string ModuleConfiguration_GetModuleContextConfigurationSection__OpenConfigurationSectionFailed {
            get {
                return ResourceManager.GetString("ModuleConfiguration_GetModuleContextConfigurationSection__OpenConfigurationSectio" +
                        "nFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The configuration file specified by the Path parameter does not exist..
        /// </summary>
        internal static string ModuleConfiguration_ResolveConfigurationFileInfo__FileDoesNotExist {
            get {
                return ResourceManager.GetString("ModuleConfiguration_ResolveConfigurationFileInfo__FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The configuration file specified by the Path parameter must be a file and not a directory..
        /// </summary>
        internal static string ModuleConfiguration_ResolveConfigurationFileInfo__FileInfoIsDirectory {
            get {
                return ResourceManager.GetString("ModuleConfiguration_ResolveConfigurationFileInfo__FileInfoIsDirectory", resourceCulture);
            }
        }
    }
}
