//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 3/31/2017 8:37:11 AM
namespace Net.Appclusive.Api.Diagnostics
{
    
    /// <summary>
    /// There are no comments for Diagnostics in the schema.
    /// </summary>
    public partial class Diagnostics : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Diagnostics object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Diagnostics(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Net.Appclusive.Public.Domain.Diagnostics", "Net.Appclusive.Api.Diagnostics");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Net.Appclusive.Public.Domain", "Net.Appclusive.Api.Diagnostics.Net.Appclusive.Public.Domain");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Net.Appclusive.Api.Diagnostics.Net.Appclusive.Public.Domain", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Net.Appclusive.Public.Domain.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Net.Appclusive.Api.Diagnostics", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Net.Appclusive.Public.Domain.Diagnostics.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for CacheItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CacheItem> CacheItems
        {
            get
            {
                if ((this._CacheItems == null))
                {
                    this._CacheItems = base.CreateQuery<CacheItem>("CacheItems");
                }
                return this._CacheItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CacheItem> _CacheItems;
        /// <summary>
        /// There are no comments for WorkflowInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<WorkflowInstance> WorkflowInstances
        {
            get
            {
                if ((this._WorkflowInstances == null))
                {
                    this._WorkflowInstances = base.CreateQuery<WorkflowInstance>("WorkflowInstances");
                }
                return this._WorkflowInstances;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<WorkflowInstance> _WorkflowInstances;
        /// <summary>
        /// There are no comments for HealthChecks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<HealthCheck> HealthChecks
        {
            get
            {
                if ((this._HealthChecks == null))
                {
                    this._HealthChecks = base.CreateQuery<HealthCheck>("HealthChecks");
                }
                return this._HealthChecks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<HealthCheck> _HealthChecks;
        /// <summary>
        /// There are no comments for CacheItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCacheItems(CacheItem cacheItem)
        {
            base.AddObject("CacheItems", cacheItem);
        }
        /// <summary>
        /// There are no comments for WorkflowInstances in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWorkflowInstances(WorkflowInstance workflowInstance)
        {
            base.AddObject("WorkflowInstances", workflowInstance);
        }
        /// <summary>
        /// There are no comments for HealthChecks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHealthChecks(HealthCheck healthCheck)
        {
            base.AddObject("HealthChecks", healthCheck);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Net.Appclusive.Public.Domain.Diagnostics\" xmlns=\"http://schemas.micro" +
                "soft.com/ado/2009/11/edm\"><EntityType Name=\"CacheItem\"><Key><PropertyRef Name=\"I" +
                "d\" /></Key><Property Name=\"Value\" Type=\"Edm.String\" Nullable=\"false\" /><Property" +
                " Name=\"Id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.S" +
                "tring\" Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Navi" +
                "gationProperty Name=\"Details\" Relationship=\"Net.Appclusive.Public.Domain.Net_App" +
                "clusive_Public_Domain_Diagnostics_CacheItem_Details_Net_Appclusive_Public_Domain" +
                "_PublicEntityDetails_DetailsPartner\" ToRole=\"Details\" FromRole=\"DetailsPartner\" " +
                "/></EntityType><EntityType Name=\"WorkflowInstance\"><Key><PropertyRef Name=\"Id\" /" +
                "></Key><Property Name=\"WorkflowInstanceId\" Type=\"Edm.Guid\" Nullable=\"false\" /><P" +
                "roperty Name=\"SurrogateInstanceId\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property" +
                " Name=\"SurrogateLockOwnerId\" Type=\"Edm.Int64\" /><Property Name=\"PrimitiveDataPro" +
                "perties\" Type=\"Edm.String\" /><Property Name=\"ComplexDataProperties\" Type=\"Edm.St" +
                "ring\" /><Property Name=\"WriteOnlyPrimitiveDataProperties\" Type=\"Edm.String\" /><P" +
                "roperty Name=\"WriteOnlyComplexDataProperties\" Type=\"Edm.String\" /><Property Name" +
                "=\"MetadataProperties\" Type=\"Edm.String\" /><Property Name=\"DataEncodingOption\" Ty" +
                "pe=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"MetadataEncodingOption\" Type" +
                "=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Version\" Type=\"Edm.Int64\" Null" +
                "able=\"false\" /><Property Name=\"PendingTimer\" Type=\"Edm.DateTimeOffset\" /><Proper" +
                "ty Name=\"WorkflowHostType\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Se" +
                "rviceDeploymentId\" Type=\"Edm.Int64\" /><Property Name=\"SuspensionExceptionName\" T" +
                "ype=\"Edm.String\" /><Property Name=\"SuspensionReason\" Type=\"Edm.String\" /><Proper" +
                "ty Name=\"BlockingBookmarks\" Type=\"Edm.String\" /><Property Name=\"LastMachineRunOn" +
                "\" Type=\"Edm.String\" /><Property Name=\"IsInitialized\" Type=\"Edm.Boolean\" Nullable" +
                "=\"false\" /><Property Name=\"IsSuspended\" Type=\"Edm.Boolean\" Nullable=\"false\" /><P" +
                "roperty Name=\"IsReadyToRun\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name" +
                "=\"IsCompleted\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"SurrogateId" +
                "entityId\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int6" +
                "4\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /" +
                "><Property Name=\"Description\" Type=\"Edm.String\" /><NavigationProperty Name=\"Deta" +
                "ils\" Relationship=\"Net.Appclusive.Public.Domain.Net_Appclusive_Public_Domain_Dia" +
                "gnostics_WorkflowInstance_Details_Net_Appclusive_Public_Domain_PublicEntityDetai" +
                "ls_DetailsPartner\" ToRole=\"Details\" FromRole=\"DetailsPartner\" /></EntityType><En" +
                "tityType Name=\"HealthCheck\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"" +
                "Status\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Id\" Type=\"Edm.Int64" +
                "\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" />" +
                "<Property Name=\"Description\" Type=\"Edm.String\" /><NavigationProperty Name=\"Detai" +
                "ls\" Relationship=\"Net.Appclusive.Public.Domain.Net_Appclusive_Public_Domain_Diag" +
                "nostics_HealthCheck_Details_Net_Appclusive_Public_Domain_PublicEntityDetails_Det" +
                "ailsPartner\" ToRole=\"Details\" FromRole=\"DetailsPartner\" /></EntityType></Schema>" +
                "<Schema Namespace=\"Net.Appclusive.Public.Domain\" xmlns=\"http://schemas.microsoft" +
                ".com/ado/2009/11/edm\"><EntityType Name=\"PublicEntityDetails\"><Key><PropertyRef N" +
                "ame=\"RowVersion\" /></Key><Property Name=\"Tid\" Type=\"Edm.Guid\" Nullable=\"false\" /" +
                "><Property Name=\"CreatedById\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name" +
                "=\"ModifiedById\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Created\" Typ" +
                "e=\"Edm.DateTimeOffset\" Nullable=\"false\" /><Property Name=\"Modified\" Type=\"Edm.Da" +
                "teTimeOffset\" Nullable=\"false\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" N" +
                "ullable=\"false\" /></EntityType><Association Name=\"Net_Appclusive_Public_Domain_D" +
                "iagnostics_CacheItem_Details_Net_Appclusive_Public_Domain_PublicEntityDetails_De" +
                "tailsPartner\"><End Type=\"Net.Appclusive.Public.Domain.PublicEntityDetails\" Role=" +
                "\"Details\" Multiplicity=\"0..1\" /><End Type=\"Net.Appclusive.Public.Domain.Diagnost" +
                "ics.CacheItem\" Role=\"DetailsPartner\" Multiplicity=\"0..1\" /></Association><Associ" +
                "ation Name=\"Net_Appclusive_Public_Domain_Diagnostics_WorkflowInstance_Details_Ne" +
                "t_Appclusive_Public_Domain_PublicEntityDetails_DetailsPartner\"><End Type=\"Net.Ap" +
                "pclusive.Public.Domain.PublicEntityDetails\" Role=\"Details\" Multiplicity=\"0..1\" /" +
                "><End Type=\"Net.Appclusive.Public.Domain.Diagnostics.WorkflowInstance\" Role=\"Det" +
                "ailsPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"Net_Appclusi" +
                "ve_Public_Domain_Diagnostics_HealthCheck_Details_Net_Appclusive_Public_Domain_Pu" +
                "blicEntityDetails_DetailsPartner\"><End Type=\"Net.Appclusive.Public.Domain.Public" +
                "EntityDetails\" Role=\"Details\" Multiplicity=\"0..1\" /><End Type=\"Net.Appclusive.Pu" +
                "blic.Domain.Diagnostics.HealthCheck\" Role=\"DetailsPartner\" Multiplicity=\"0..1\" /" +
                "></Association></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas.micros" +
                "oft.com/ado/2009/11/edm\"><EntityContainer Name=\"Diagnostics\" m:IsDefaultEntityCo" +
                "ntainer=\"true\"><EntitySet Name=\"CacheItems\" EntityType=\"Net.Appclusive.Public.Do" +
                "main.Diagnostics.CacheItem\" /><EntitySet Name=\"WorkflowInstances\" EntityType=\"Ne" +
                "t.Appclusive.Public.Domain.Diagnostics.WorkflowInstance\" /><EntitySet Name=\"Heal" +
                "thChecks\" EntityType=\"Net.Appclusive.Public.Domain.Diagnostics.HealthCheck\" /><F" +
                "unctionImport Name=\"Template\" ReturnType=\"Net.Appclusive.Public.Domain.Diagnosti" +
                "cs.CacheItem\" IsBindable=\"true\" EntitySet=\"CacheItems\" m:IsAlwaysBindable=\"true\"" +
                "><Parameter Name=\"bindingParameter\" Type=\"Collection(Net.Appclusive.Public.Domai" +
                "n.Diagnostics.CacheItem)\" Nullable=\"false\" /></FunctionImport><FunctionImport Na" +
                "me=\"Template\" ReturnType=\"Net.Appclusive.Public.Domain.Diagnostics.WorkflowInsta" +
                "nce\" IsBindable=\"true\" EntitySet=\"WorkflowInstances\" m:IsAlwaysBindable=\"true\"><" +
                "Parameter Name=\"bindingParameter\" Type=\"Collection(Net.Appclusive.Public.Domain." +
                "Diagnostics.WorkflowInstance)\" Nullable=\"false\" /></FunctionImport><FunctionImpo" +
                "rt Name=\"Template\" ReturnType=\"Net.Appclusive.Public.Domain.Diagnostics.HealthCh" +
                "eck\" IsBindable=\"true\" EntitySet=\"HealthChecks\" m:IsAlwaysBindable=\"true\"><Param" +
                "eter Name=\"bindingParameter\" Type=\"Collection(Net.Appclusive.Public.Domain.Diagn" +
                "ostics.HealthCheck)\" Nullable=\"false\" /></FunctionImport></EntityContainer></Sch" +
                "ema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Net.Appclusive.Public.Domain.Diagnostics.CacheItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CacheItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CacheItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CacheItem object.
        /// </summary>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CacheItem CreateCacheItem(string value, long ID, string name)
        {
            CacheItem cacheItem = new CacheItem();
            cacheItem.Value = value;
            cacheItem.Id = ID;
            cacheItem.Name = name;
            return cacheItem;
        }
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Net.Appclusive.Public.Domain.PublicEntityDetails Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                this._Details = value;
                this.OnPropertyChanged("Details");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Net.Appclusive.Public.Domain.PublicEntityDetails _Details;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Net.Appclusive.Public.Domain.Diagnostics.WorkflowInstance in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("WorkflowInstances")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class WorkflowInstance : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WorkflowInstance object.
        /// </summary>
        /// <param name="workflowInstanceId">Initial value of WorkflowInstanceId.</param>
        /// <param name="surrogateInstanceId">Initial value of SurrogateInstanceId.</param>
        /// <param name="dataEncodingOption">Initial value of DataEncodingOption.</param>
        /// <param name="metadataEncodingOption">Initial value of MetadataEncodingOption.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="workflowHostType">Initial value of WorkflowHostType.</param>
        /// <param name="isInitialized">Initial value of IsInitialized.</param>
        /// <param name="isSuspended">Initial value of IsSuspended.</param>
        /// <param name="isReadyToRun">Initial value of IsReadyToRun.</param>
        /// <param name="isCompleted">Initial value of IsCompleted.</param>
        /// <param name="surrogateIdentityId">Initial value of SurrogateIdentityId.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static WorkflowInstance CreateWorkflowInstance(global::System.Guid workflowInstanceId, long surrogateInstanceId, bool dataEncodingOption, bool metadataEncodingOption, long version, global::System.Guid workflowHostType, bool isInitialized, bool isSuspended, bool isReadyToRun, bool isCompleted, long surrogateIdentityId, long ID, string name)
        {
            WorkflowInstance workflowInstance = new WorkflowInstance();
            workflowInstance.WorkflowInstanceId = workflowInstanceId;
            workflowInstance.SurrogateInstanceId = surrogateInstanceId;
            workflowInstance.DataEncodingOption = dataEncodingOption;
            workflowInstance.MetadataEncodingOption = metadataEncodingOption;
            workflowInstance.Version = version;
            workflowInstance.WorkflowHostType = workflowHostType;
            workflowInstance.IsInitialized = isInitialized;
            workflowInstance.IsSuspended = isSuspended;
            workflowInstance.IsReadyToRun = isReadyToRun;
            workflowInstance.IsCompleted = isCompleted;
            workflowInstance.SurrogateIdentityId = surrogateIdentityId;
            workflowInstance.Id = ID;
            workflowInstance.Name = name;
            return workflowInstance;
        }
        /// <summary>
        /// There are no comments for Property WorkflowInstanceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid WorkflowInstanceId
        {
            get
            {
                return this._WorkflowInstanceId;
            }
            set
            {
                this.OnWorkflowInstanceIdChanging(value);
                this._WorkflowInstanceId = value;
                this.OnWorkflowInstanceIdChanged();
                this.OnPropertyChanged("WorkflowInstanceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _WorkflowInstanceId;
        partial void OnWorkflowInstanceIdChanging(global::System.Guid value);
        partial void OnWorkflowInstanceIdChanged();
        /// <summary>
        /// There are no comments for Property SurrogateInstanceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long SurrogateInstanceId
        {
            get
            {
                return this._SurrogateInstanceId;
            }
            set
            {
                this.OnSurrogateInstanceIdChanging(value);
                this._SurrogateInstanceId = value;
                this.OnSurrogateInstanceIdChanged();
                this.OnPropertyChanged("SurrogateInstanceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _SurrogateInstanceId;
        partial void OnSurrogateInstanceIdChanging(long value);
        partial void OnSurrogateInstanceIdChanged();
        /// <summary>
        /// There are no comments for Property SurrogateLockOwnerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> SurrogateLockOwnerId
        {
            get
            {
                return this._SurrogateLockOwnerId;
            }
            set
            {
                this.OnSurrogateLockOwnerIdChanging(value);
                this._SurrogateLockOwnerId = value;
                this.OnSurrogateLockOwnerIdChanged();
                this.OnPropertyChanged("SurrogateLockOwnerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _SurrogateLockOwnerId;
        partial void OnSurrogateLockOwnerIdChanging(global::System.Nullable<long> value);
        partial void OnSurrogateLockOwnerIdChanged();
        /// <summary>
        /// There are no comments for Property PrimitiveDataProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PrimitiveDataProperties
        {
            get
            {
                return this._PrimitiveDataProperties;
            }
            set
            {
                this.OnPrimitiveDataPropertiesChanging(value);
                this._PrimitiveDataProperties = value;
                this.OnPrimitiveDataPropertiesChanged();
                this.OnPropertyChanged("PrimitiveDataProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PrimitiveDataProperties;
        partial void OnPrimitiveDataPropertiesChanging(string value);
        partial void OnPrimitiveDataPropertiesChanged();
        /// <summary>
        /// There are no comments for Property ComplexDataProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ComplexDataProperties
        {
            get
            {
                return this._ComplexDataProperties;
            }
            set
            {
                this.OnComplexDataPropertiesChanging(value);
                this._ComplexDataProperties = value;
                this.OnComplexDataPropertiesChanged();
                this.OnPropertyChanged("ComplexDataProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ComplexDataProperties;
        partial void OnComplexDataPropertiesChanging(string value);
        partial void OnComplexDataPropertiesChanged();
        /// <summary>
        /// There are no comments for Property WriteOnlyPrimitiveDataProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WriteOnlyPrimitiveDataProperties
        {
            get
            {
                return this._WriteOnlyPrimitiveDataProperties;
            }
            set
            {
                this.OnWriteOnlyPrimitiveDataPropertiesChanging(value);
                this._WriteOnlyPrimitiveDataProperties = value;
                this.OnWriteOnlyPrimitiveDataPropertiesChanged();
                this.OnPropertyChanged("WriteOnlyPrimitiveDataProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WriteOnlyPrimitiveDataProperties;
        partial void OnWriteOnlyPrimitiveDataPropertiesChanging(string value);
        partial void OnWriteOnlyPrimitiveDataPropertiesChanged();
        /// <summary>
        /// There are no comments for Property WriteOnlyComplexDataProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WriteOnlyComplexDataProperties
        {
            get
            {
                return this._WriteOnlyComplexDataProperties;
            }
            set
            {
                this.OnWriteOnlyComplexDataPropertiesChanging(value);
                this._WriteOnlyComplexDataProperties = value;
                this.OnWriteOnlyComplexDataPropertiesChanged();
                this.OnPropertyChanged("WriteOnlyComplexDataProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WriteOnlyComplexDataProperties;
        partial void OnWriteOnlyComplexDataPropertiesChanging(string value);
        partial void OnWriteOnlyComplexDataPropertiesChanged();
        /// <summary>
        /// There are no comments for Property MetadataProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MetadataProperties
        {
            get
            {
                return this._MetadataProperties;
            }
            set
            {
                this.OnMetadataPropertiesChanging(value);
                this._MetadataProperties = value;
                this.OnMetadataPropertiesChanged();
                this.OnPropertyChanged("MetadataProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MetadataProperties;
        partial void OnMetadataPropertiesChanging(string value);
        partial void OnMetadataPropertiesChanged();
        /// <summary>
        /// There are no comments for Property DataEncodingOption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool DataEncodingOption
        {
            get
            {
                return this._DataEncodingOption;
            }
            set
            {
                this.OnDataEncodingOptionChanging(value);
                this._DataEncodingOption = value;
                this.OnDataEncodingOptionChanged();
                this.OnPropertyChanged("DataEncodingOption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _DataEncodingOption;
        partial void OnDataEncodingOptionChanging(bool value);
        partial void OnDataEncodingOptionChanged();
        /// <summary>
        /// There are no comments for Property MetadataEncodingOption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool MetadataEncodingOption
        {
            get
            {
                return this._MetadataEncodingOption;
            }
            set
            {
                this.OnMetadataEncodingOptionChanging(value);
                this._MetadataEncodingOption = value;
                this.OnMetadataEncodingOptionChanged();
                this.OnPropertyChanged("MetadataEncodingOption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _MetadataEncodingOption;
        partial void OnMetadataEncodingOptionChanging(bool value);
        partial void OnMetadataEncodingOptionChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Version;
        partial void OnVersionChanging(long value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property PendingTimer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> PendingTimer
        {
            get
            {
                return this._PendingTimer;
            }
            set
            {
                this.OnPendingTimerChanging(value);
                this._PendingTimer = value;
                this.OnPendingTimerChanged();
                this.OnPropertyChanged("PendingTimer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _PendingTimer;
        partial void OnPendingTimerChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnPendingTimerChanged();
        /// <summary>
        /// There are no comments for Property WorkflowHostType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid WorkflowHostType
        {
            get
            {
                return this._WorkflowHostType;
            }
            set
            {
                this.OnWorkflowHostTypeChanging(value);
                this._WorkflowHostType = value;
                this.OnWorkflowHostTypeChanged();
                this.OnPropertyChanged("WorkflowHostType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _WorkflowHostType;
        partial void OnWorkflowHostTypeChanging(global::System.Guid value);
        partial void OnWorkflowHostTypeChanged();
        /// <summary>
        /// There are no comments for Property ServiceDeploymentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ServiceDeploymentId
        {
            get
            {
                return this._ServiceDeploymentId;
            }
            set
            {
                this.OnServiceDeploymentIdChanging(value);
                this._ServiceDeploymentId = value;
                this.OnServiceDeploymentIdChanged();
                this.OnPropertyChanged("ServiceDeploymentId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ServiceDeploymentId;
        partial void OnServiceDeploymentIdChanging(global::System.Nullable<long> value);
        partial void OnServiceDeploymentIdChanged();
        /// <summary>
        /// There are no comments for Property SuspensionExceptionName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SuspensionExceptionName
        {
            get
            {
                return this._SuspensionExceptionName;
            }
            set
            {
                this.OnSuspensionExceptionNameChanging(value);
                this._SuspensionExceptionName = value;
                this.OnSuspensionExceptionNameChanged();
                this.OnPropertyChanged("SuspensionExceptionName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SuspensionExceptionName;
        partial void OnSuspensionExceptionNameChanging(string value);
        partial void OnSuspensionExceptionNameChanged();
        /// <summary>
        /// There are no comments for Property SuspensionReason in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SuspensionReason
        {
            get
            {
                return this._SuspensionReason;
            }
            set
            {
                this.OnSuspensionReasonChanging(value);
                this._SuspensionReason = value;
                this.OnSuspensionReasonChanged();
                this.OnPropertyChanged("SuspensionReason");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SuspensionReason;
        partial void OnSuspensionReasonChanging(string value);
        partial void OnSuspensionReasonChanged();
        /// <summary>
        /// There are no comments for Property BlockingBookmarks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BlockingBookmarks
        {
            get
            {
                return this._BlockingBookmarks;
            }
            set
            {
                this.OnBlockingBookmarksChanging(value);
                this._BlockingBookmarks = value;
                this.OnBlockingBookmarksChanged();
                this.OnPropertyChanged("BlockingBookmarks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BlockingBookmarks;
        partial void OnBlockingBookmarksChanging(string value);
        partial void OnBlockingBookmarksChanged();
        /// <summary>
        /// There are no comments for Property LastMachineRunOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastMachineRunOn
        {
            get
            {
                return this._LastMachineRunOn;
            }
            set
            {
                this.OnLastMachineRunOnChanging(value);
                this._LastMachineRunOn = value;
                this.OnLastMachineRunOnChanged();
                this.OnPropertyChanged("LastMachineRunOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastMachineRunOn;
        partial void OnLastMachineRunOnChanging(string value);
        partial void OnLastMachineRunOnChanged();
        /// <summary>
        /// There are no comments for Property IsInitialized in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsInitialized
        {
            get
            {
                return this._IsInitialized;
            }
            set
            {
                this.OnIsInitializedChanging(value);
                this._IsInitialized = value;
                this.OnIsInitializedChanged();
                this.OnPropertyChanged("IsInitialized");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsInitialized;
        partial void OnIsInitializedChanging(bool value);
        partial void OnIsInitializedChanged();
        /// <summary>
        /// There are no comments for Property IsSuspended in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsSuspended
        {
            get
            {
                return this._IsSuspended;
            }
            set
            {
                this.OnIsSuspendedChanging(value);
                this._IsSuspended = value;
                this.OnIsSuspendedChanged();
                this.OnPropertyChanged("IsSuspended");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsSuspended;
        partial void OnIsSuspendedChanging(bool value);
        partial void OnIsSuspendedChanged();
        /// <summary>
        /// There are no comments for Property IsReadyToRun in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsReadyToRun
        {
            get
            {
                return this._IsReadyToRun;
            }
            set
            {
                this.OnIsReadyToRunChanging(value);
                this._IsReadyToRun = value;
                this.OnIsReadyToRunChanged();
                this.OnPropertyChanged("IsReadyToRun");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsReadyToRun;
        partial void OnIsReadyToRunChanging(bool value);
        partial void OnIsReadyToRunChanged();
        /// <summary>
        /// There are no comments for Property IsCompleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsCompleted
        {
            get
            {
                return this._IsCompleted;
            }
            set
            {
                this.OnIsCompletedChanging(value);
                this._IsCompleted = value;
                this.OnIsCompletedChanged();
                this.OnPropertyChanged("IsCompleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsCompleted;
        partial void OnIsCompletedChanging(bool value);
        partial void OnIsCompletedChanged();
        /// <summary>
        /// There are no comments for Property SurrogateIdentityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long SurrogateIdentityId
        {
            get
            {
                return this._SurrogateIdentityId;
            }
            set
            {
                this.OnSurrogateIdentityIdChanging(value);
                this._SurrogateIdentityId = value;
                this.OnSurrogateIdentityIdChanged();
                this.OnPropertyChanged("SurrogateIdentityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _SurrogateIdentityId;
        partial void OnSurrogateIdentityIdChanging(long value);
        partial void OnSurrogateIdentityIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Net.Appclusive.Public.Domain.PublicEntityDetails Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                this._Details = value;
                this.OnPropertyChanged("Details");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Net.Appclusive.Public.Domain.PublicEntityDetails _Details;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Net.Appclusive.Public.Domain.Diagnostics.HealthCheck in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("HealthChecks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class HealthCheck : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new HealthCheck object.
        /// </summary>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static HealthCheck CreateHealthCheck(string status, long ID, string name)
        {
            HealthCheck healthCheck = new HealthCheck();
            healthCheck.Status = status;
            healthCheck.Id = ID;
            healthCheck.Name = name;
            return healthCheck;
        }
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Net.Appclusive.Public.Domain.PublicEntityDetails Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                this._Details = value;
                this.OnPropertyChanged("Details");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Net.Appclusive.Public.Domain.PublicEntityDetails _Details;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
// Original file name:
// Generation date: 3/31/2017 8:37:11 AM
namespace Net.Appclusive.Public.Domain
{
    
    /// <summary>
    /// There are no comments for Net.Appclusive.Public.Domain.PublicEntityDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RowVersion
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("RowVersion")]
    public partial class PublicEntityDetails : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PublicEntityDetails object.
        /// </summary>
        /// <param name="tid">Initial value of Tid.</param>
        /// <param name="createdById">Initial value of CreatedById.</param>
        /// <param name="modifiedById">Initial value of ModifiedById.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="modified">Initial value of Modified.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PublicEntityDetails CreatePublicEntityDetails(global::System.Guid tid, long createdById, long modifiedById, global::System.DateTimeOffset created, global::System.DateTimeOffset modified, byte[] rowVersion)
        {
            PublicEntityDetails publicEntityDetails = new PublicEntityDetails();
            publicEntityDetails.Tid = tid;
            publicEntityDetails.CreatedById = createdById;
            publicEntityDetails.ModifiedById = modifiedById;
            publicEntityDetails.Created = created;
            publicEntityDetails.Modified = modified;
            publicEntityDetails.RowVersion = rowVersion;
            return publicEntityDetails;
        }
        /// <summary>
        /// There are no comments for Property Tid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Tid
        {
            get
            {
                return this._Tid;
            }
            set
            {
                this.OnTidChanging(value);
                this._Tid = value;
                this.OnTidChanged();
                this.OnPropertyChanged("Tid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Tid;
        partial void OnTidChanging(global::System.Guid value);
        partial void OnTidChanged();
        /// <summary>
        /// There are no comments for Property CreatedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long CreatedById
        {
            get
            {
                return this._CreatedById;
            }
            set
            {
                this.OnCreatedByIdChanging(value);
                this._CreatedById = value;
                this.OnCreatedByIdChanged();
                this.OnPropertyChanged("CreatedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _CreatedById;
        partial void OnCreatedByIdChanging(long value);
        partial void OnCreatedByIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedById in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ModifiedById
        {
            get
            {
                return this._ModifiedById;
            }
            set
            {
                this.OnModifiedByIdChanging(value);
                this._ModifiedById = value;
                this.OnModifiedByIdChanged();
                this.OnPropertyChanged("ModifiedById");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ModifiedById;
        partial void OnModifiedByIdChanging(long value);
        partial void OnModifiedByIdChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Created;
        partial void OnCreatedChanging(global::System.DateTimeOffset value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTimeOffset Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTimeOffset _Modified;
        partial void OnModifiedChanging(global::System.DateTimeOffset value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
